export const countries = [
  { code: 'AF', label: 'Afghanistan', phoneCode: '+93', flag: '🇦🇫' },
  { code: 'AL', label: 'Albania', phoneCode: '+355', flag: '🇦🇱' },
  { code: 'DZ', label: 'Algeria', phoneCode: '+213', flag: '🇩🇿' },
  { code: 'AS', label: 'American Samoa', phoneCode: '+1-684', flag: '🇦🇸' },
  { code: 'AD', label: 'Andorra', phoneCode: '+376', flag: '🇦🇩' },
  { code: 'AO', label: 'Angola', phoneCode: '+244', flag: '🇦🇴' },
  { code: 'AI', label: 'Anguilla', phoneCode: '+1-264', flag: '🇦🇮' },
  { code: 'AG', label: 'Antigua and Barbuda', phoneCode: '+1-268', flag: '🇦🇬' },
  { code: 'AR', label: 'Argentina', phoneCode: '+54', flag: '🇦🇷' },
  { code: 'AM', label: 'Armenia', phoneCode: '+374', flag: '🇦🇲' },
  { code: 'AW', label: 'Aruba', phoneCode: '+297', flag: '🇦🇼' },
  { code: 'AU', label: 'Australia', phoneCode: '+61', flag: '🇦🇺' },
  { code: 'AT', label: 'Austria', phoneCode: '+43', flag: '🇦🇹' },
  { code: 'AZ', label: 'Azerbaijan', phoneCode: '+994', flag: '🇦🇿' },
  { code: 'BS', label: 'Bahamas', phoneCode: '+1-242', flag: '🇧🇸' },
  { code: 'BH', label: 'Bahrain', phoneCode: '+973', flag: '🇧🇭' },
  { code: 'BD', label: 'Bangladesh', phoneCode: '+880', flag: '🇧🇩' },
  { code: 'BB', label: 'Barbados', phoneCode: '+1-246', flag: '🇧🇧' },
  { code: 'BY', label: 'Belarus', phoneCode: '+375', flag: '🇧🇾' },
  { code: 'BE', label: 'Belgium', phoneCode: '+32', flag: '🇧🇪' },
  { code: 'BZ', label: 'Belize', phoneCode: '+501', flag: '🇧🇿' },
  { code: 'BJ', label: 'Benin', phoneCode: '+229', flag: '🇧🇯' },
  { code: 'BM', label: 'Bermuda', phoneCode: '+1-441', flag: '🇧🇲' },
  { code: 'BT', label: 'Bhutan', phoneCode: '+975', flag: '🇧🇹' },
  { code: 'BO', label: 'Bolivia', phoneCode: '+591', flag: '🇧🇴' },
  { code: 'BA', label: 'Bosnia and Herzegovina', phoneCode: '+387', flag: '🇧🇦' },
  { code: 'BW', label: 'Botswana', phoneCode: '+267', flag: '🇧🇼' },
  { code: 'BR', label: 'Brazil', phoneCode: '+55', flag: '🇧🇷' },
  { code: 'IO', label: 'British Indian Ocean Territory', phoneCode: '+246', flag: '🇮🇴' },
  { code: 'VG', label: 'British Virgin Islands', phoneCode: '+1-284', flag: '🇻🇬' },
  { code: 'BN', label: 'Brunei', phoneCode: '+673', flag: '🇧🇳' },
  { code: 'BG', label: 'Bulgaria', phoneCode: '+359', flag: '🇧🇬' },
  { code: 'BF', label: 'Burkina Faso', phoneCode: '+226', flag: '🇧🇫' },
  { code: 'BI', label: 'Burundi', phoneCode: '+257', flag: '🇧🇮' },
  { code: 'KH', label: 'Cambodia', phoneCode: '+855', flag: '🇰🇭' },
  { code: 'CM', label: 'Cameroon', phoneCode: '+237', flag: '🇨🇲' },
  { code: 'CA', label: 'Canada', phoneCode: '+1', flag: '🇨🇦' },
  { code: 'CV', label: 'Cape Verde', phoneCode: '+238', flag: '🇨🇻' },
  { code: 'KY', label: 'Cayman Islands', phoneCode: '+1-345', flag: '🇰🇾' },
  { code: 'CF', label: 'Central African Republic', phoneCode: '+236', flag: '🇨🇫' },
  { code: 'TD', label: 'Chad', phoneCode: '+235', flag: '🇹🇩' },
  { code: 'CL', label: 'Chile', phoneCode: '+56', flag: '🇨🇱' },
  { code: 'CN', label: 'China', phoneCode: '+86', flag: '🇨🇳' },
  { code: 'CX', label: 'Christmas Island', phoneCode: '+61', flag: '🇨🇽' },
  { code: 'CC', label: 'Cocos (Keeling) Islands', phoneCode: '+61', flag: '🇨🇨' },
  { code: 'CO', label: 'Colombia', phoneCode: '+57', flag: '🇨🇴' },
  { code: 'KM', label: 'Comoros', phoneCode: '+269', flag: '🇰🇲' },
  { code: 'CG', label: 'Congo', phoneCode: '+242', flag: '🇨🇬' },
  { code: 'CD', label: 'Congo (Democratic Republic)', phoneCode: '+243', flag: '🇨🇩' },
  { code: 'CR', label: 'Costa Rica', phoneCode: '+506', flag: '🇨🇷' },
  { code: 'HR', label: 'Croatia', phoneCode: '+385', flag: '🇭🇷' },
  { code: 'CU', label: 'Cuba', phoneCode: '+53', flag: '🇨🇺' },
  { code: 'CY', label: 'Cyprus', phoneCode: '+357', flag: '🇨🇾' },
  { code: 'CZ', label: 'Czech Republic', phoneCode: '+420', flag: '🇨🇿' },
  { code: 'DK', label: 'Denmark', phoneCode: '+45', flag: '🇩🇰' },
  { code: 'DJ', label: 'Djibouti', phoneCode: '+253', flag: '🇩🇯' },
  { code: 'DM', label: 'Dominica', phoneCode: '+1-767', flag: '🇩🇲' },
  { code: 'DO', label: 'Dominican Republic', phoneCode: '+1-809', flag: '🇩🇴' },
  { code: 'EC', label: 'Ecuador', phoneCode: '+593', flag: '🇪🇨' },
  { code: 'EG', label: 'Egypt', phoneCode: '+20', flag: '🇪🇬' },
  { code: 'SV', label: 'El Salvador', phoneCode: '+503', flag: '🇸🇻' },
  { code: 'GQ', label: 'Equatorial Guinea', phoneCode: '+240', flag: '🇬🇶' },
  { code: 'ER', label: 'Eritrea', phoneCode: '+291', flag: '🇪🇷' },
  { code: 'EE', label: 'Estonia', phoneCode: '+372', flag: '🇪🇪' },
  { code: 'ET', label: 'Ethiopia', phoneCode: '+251', flag: '🇪🇹' },
  { code: 'FJ', label: 'Fiji', phoneCode: '+679', flag: '🇫🇯' },
  { code: 'FI', label: 'Finland', phoneCode: '+358', flag: '🇫🇮' },
  { code: 'FR', label: 'France', phoneCode: '+33', flag: '🇫🇷' },
  { code: 'GF', label: 'French Guiana', phoneCode: '+594', flag: '🇬🇫' },
  { code: 'PF', label: 'French Polynesia', phoneCode: '+689', flag: '🇵🇫' },
  { code: 'TF', label: 'French Southern and Antarctic Lands', phoneCode: '+262', flag: '🇹🇫' },
  { code: 'GA', label: 'Gabon', phoneCode: '+241', flag: '🇬🇦' },
  { code: 'GM', label: 'Gambia', phoneCode: '+220', flag: '🇬🇲' },
  { code: 'GE', label: 'Georgia', phoneCode: '+995', flag: '🇬🇪' },
  { code: 'DE', label: 'Germany', phoneCode: '+49', flag: '🇩🇪' },
  { code: 'GH', label: 'Ghana', phoneCode: '+233', flag: '🇬🇭' },
  { code: 'GR', label: 'Greece', phoneCode: '+30', flag: '🇬🇷' },
  { code: 'GD', label: 'Grenada', phoneCode: '+1-473', flag: '🇬🇩' },
  { code: 'GT', label: 'Guatemala', phoneCode: '+502', flag: '🇬🇹' },
  { code: 'GN', label: 'Guinea', phoneCode: '+224', flag: '🇬🇳' },
  { code: 'GW', label: 'Guinea-Bissau', phoneCode: '+245', flag: '🇬🇼' },
  { code: 'GY', label: 'Guyana', phoneCode: '+592', flag: '🇬🇾' },
  { code: 'HT', label: 'Haiti', phoneCode: '+509', flag: '🇭🇹' },
  { code: 'HN', label: 'Honduras', phoneCode: '+504', flag: '🇭🇳' },
  { code: 'HK', label: 'Hong Kong', phoneCode: '+852', flag: '🇭🇰' },
  { code: 'HU', label: 'Hungary', phoneCode: '+36', flag: '🇭🇺' },
  { code: 'IS', label: 'Iceland', phoneCode: '+354', flag: '🇮🇸' },
  { code: 'IN', label: 'India', phoneCode: '+91', flag: '🇮🇳' },
  { code: 'ID', label: 'Indonesia', phoneCode: '+62', flag: '🇮🇩' },
  { code: 'IR', label: 'Iran', phoneCode: '+98', flag: '🇮🇷' },
  { code: 'IQ', label: 'Iraq', phoneCode: '+964', flag: '🇮🇶' },
  { code: 'IE', label: 'Ireland', phoneCode: '+353', flag: '🇮🇪' },
  { code: 'IL', label: 'Israel', phoneCode: '+972', flag: '🇮🇱' },
  { code: 'IT', label: 'Italy', phoneCode: '+39', flag: '🇮🇹' },
  { code: 'CI', label: 'Ivory Coast', phoneCode: '+225', flag: '🇨🇮' },
  { code: 'JM', label: 'Jamaica', phoneCode: '+1-876', flag: '🇯🇲' },
  { code: 'JP', label: 'Japan', phoneCode: '+81', flag: '🇯🇵' },
  { code: 'JO', label: 'Jordan', phoneCode: '+962', flag: '🇯🇴' },
  { code: 'KZ', label: 'Kazakhstan', phoneCode: '+7', flag: '🇰🇿' },
  { code: 'KE', label: 'Kenya', phoneCode: '+254', flag: '🇰🇪' },
  { code: 'KI', label: 'Kiribati', phoneCode: '+686', flag: '🇰🇮' },
  { code: 'KR', label: 'South Korea', phoneCode: '+82', flag: '🇰🇷' },
  { code: 'KW', label: 'Kuwait', phoneCode: '+965', flag: '🇰🇼' },
  { code: 'KG', label: 'Kyrgyzstan', phoneCode: '+996', flag: '🇰🇬' },
  { code: 'LA', label: 'Laos', phoneCode: '+856', flag: '🇱🇦' },
  { code: 'LV', label: 'Latvia', phoneCode: '+371', flag: '🇱🇻' },
  { code: 'LB', label: 'Lebanon', phoneCode: '+961', flag: '🇱🇧' },
  { code: 'LS', label: 'Lesotho', phoneCode: '+266', flag: '🇱🇸' },
  { code: 'LR', label: 'Liberia', phoneCode: '+231', flag: '🇱🇷' },
  { code: 'LY', label: 'Libya', phoneCode: '+218', flag: '🇱🇾' },
  { code: 'LI', label: 'Liechtenstein', phoneCode: '+423', flag: '🇱🇮' },
  { code: 'LT', label: 'Lithuania', phoneCode: '+370', flag: '🇱🇹' },
  { code: 'LU', label: 'Luxembourg', phoneCode: '+352', flag: '🇱🇺' },
  { code: 'MO', label: 'Macau', phoneCode: '+853', flag: '🇲🇴' },
  { code: 'MK', label: 'North Macedonia', phoneCode: '+389', flag: '🇲🇰' },
  { code: 'MG', label: 'Madagascar', phoneCode: '+261', flag: '🇲🇬' },
  { code: 'MW', label: 'Malawi', phoneCode: '+265', flag: '🇲🇼' },
  { code: 'MY', label: 'Malaysia', phoneCode: '+60', flag: '🇲🇾' },
  { code: 'MV', label: 'Maldives', phoneCode: '+960', flag: '🇲🇻' },
  { code: 'ML', label: 'Mali', phoneCode: '+223', flag: '🇲🇱' },
  { code: 'MT', label: 'Malta', phoneCode: '+356', flag: '🇲🇹' },
  { code: 'MH', label: 'Marshall Islands', phoneCode: '+692', flag: '🇲🇭' },
  { code: 'MQ', label: 'Martinique', phoneCode: '+596', flag: '🇲🇶' },
  { code: 'MR', label: 'Mauritania', phoneCode: '+222', flag: '🇲🇷' },
  { code: 'MU', label: 'Mauritius', phoneCode: '+230', flag: '🇲🇺' },
  { code: 'YT', label: 'Mayotte', phoneCode: '+262', flag: '🇾🇹' },
  { code: 'MX', label: 'Mexico', phoneCode: '+52', flag: '🇲🇽' },
  { code: 'FM', label: 'Micronesia', phoneCode: '+691', flag: '🇫🇲' },
  { code: 'MD', label: 'Moldova', phoneCode: '+373', flag: '🇲🇩' },
  { code: 'MC', label: 'Monaco', phoneCode: '+377', flag: '🇲🇨' },
  { code: 'MN', label: 'Mongolia', phoneCode: '+976', flag: '🇲🇳' },
  { code: 'ME', label: 'Montenegro', phoneCode: '+382', flag: '🇲🇪' },
  { code: 'MS', label: 'Montserrat', phoneCode: '+1-664', flag: '🇲🇸' },
  { code: 'MA', label: 'Morocco', phoneCode: '+212', flag: '🇲🇦' },
  { code: 'MO', label: 'Mozambique', phoneCode: '+258', flag: '🇲🇿' },
  { code: 'MM', label: 'Myanmar', phoneCode: '+95', flag: '🇲🇲' },
  { code: 'NA', label: 'Namibia', phoneCode: '+264', flag: '🇳🇦' },
  { code: 'NR', label: 'Nauru', phoneCode: '+674', flag: '🇳🇷' },
  { code: 'NP', label: 'Nepal', phoneCode: '+977', flag: '🇳🇵' },
  { code: 'NL', label: 'Netherlands', phoneCode: '+31', flag: '🇳🇱' },
  { code: 'NC', label: 'New Caledonia', phoneCode: '+687', flag: '🇳🇨' },
  { code: 'NZ', label: 'New Zealand', phoneCode: '+64', flag: '🇳🇿' },
  { code: 'NI', label: 'Nicaragua', phoneCode: '+505', flag: '🇳🇮' },
  { code: 'NE', label: 'Niger', phoneCode: '+227', flag: '🇳🇪' },
  { code: 'NG', label: 'Nigeria', phoneCode: '+234', flag: '🇳🇬' },
  { code: 'NU', label: 'Niue', phoneCode: '+683', flag: '🇳🇺' },
  { code: 'NF', label: 'Norfolk Island', phoneCode: '+6723', flag: '🇳🇫' },
  { code: 'KP', label: 'North Korea', phoneCode: '+850', flag: '🇰🇵' },
  { code: 'MP', label: 'Northern Mariana Islands', phoneCode: '+1-670', flag: '🇲🇵' },
  { code: 'NO', label: 'Norway', phoneCode: '+47', flag: '🇳🇴' },
  { code: 'OM', label: 'Oman', phoneCode: '+968', flag: '🇴🇲' },
  { code: 'PK', label: 'Pakistan', phoneCode: '+92', flag: '🇵🇰' },
  { code: 'PW', label: 'Palau', phoneCode: '+680', flag: '🇵🇼' },
  { code: 'PS', label: 'Palestinian Territories', phoneCode: '+970', flag: '🇵🇸' },
  { code: 'PA', label: 'Panama', phoneCode: '+507', flag: '🇵🇦' },
  { code: 'PG', label: 'Papua New Guinea', phoneCode: '+675', flag: '🇵🇬' },
  { code: 'PY', label: 'Paraguay', phoneCode: '+595', flag: '🇵🇾' },
  { code: 'PE', label: 'Peru', phoneCode: '+51', flag: '🇵🇪' },
  { code: 'PH', label: 'Philippines', phoneCode: '+63', flag: '🇵🇭' },
  { code: 'PL', label: 'Poland', phoneCode: '+48', flag: '🇵🇱' },
  { code: 'PT', label: 'Portugal', phoneCode: '+351', flag: '🇵🇹' },
  { code: 'PR', label: 'Puerto Rico', phoneCode: '+1-787', flag: '🇵🇷' },
  { code: 'QA', label: 'Qatar', phoneCode: '+974', flag: '🇶🇦' },
  { code: 'RO', label: 'Romania', phoneCode: '+40', flag: '🇷🇴' },
  { code: 'RU', label: 'Russia', phoneCode: '+7', flag: '🇷🇺' },
  { code: 'RW', label: 'Rwanda', phoneCode: '+250', flag: '🇷🇼' },
  { code: 'RE', label: 'Réunion', phoneCode: '+262', flag: '🇷🇪' },
  { code: 'BL', label: 'Saint Barthélemy', phoneCode: '+590', flag: '🇧🇱' },
  { code: 'SH', label: 'Saint Helena', phoneCode: '+290', flag: '🇸🇭' },
  { code: 'KN', label: 'Saint Kitts and Nevis', phoneCode: '+1-869', flag: '🇰🇳' },
  { code: 'LC', label: 'Saint Lucia', phoneCode: '+1-758', flag: '🇱🇨' },
  { code: 'MF', label: 'Saint Martin', phoneCode: '+590', flag: '🇲🇫' },
  { code: 'PM', label: 'Saint Pierre and Miquelon', phoneCode: '+508', flag: '🇵🇲' },
  { code: 'VC', label: 'Saint Vincent and the Grenadines', phoneCode: '+1-784', flag: '🇻🇨' },
  { code: 'WS', label: 'Samoa', phoneCode: '+685', flag: '🇼🇸' },
  { code: 'SM', label: 'San Marino', phoneCode: '+378', flag: '🇸🇲' },
  { code: 'ST', label: 'São Tomé and Príncipe', phoneCode: '+239', flag: '🇸🇹' },
  { code: 'SA', label: 'Saudi Arabia', phoneCode: '+966', flag: '🇸🇦' },
  { code: 'SN', label: 'Senegal', phoneCode: '+221', flag: '🇸🇳' },
  { code: 'RS', label: 'Serbia', phoneCode: '+381', flag: '🇷🇸' },
  { code: 'SC', label: 'Seychelles', phoneCode: '+248', flag: '🇸🇨' },
  { code: 'SL', label: 'Sierra Leone', phoneCode: '+232', flag: '🇸🇱' },
  { code: 'SG', label: 'Singapore', phoneCode: '+65', flag: '🇸🇬' },
  { code: 'SX', label: 'Sint Maarten', phoneCode: '+1-721', flag: '🇸🇽' },
  { code: 'SK', label: 'Slovakia', phoneCode: '+421', flag: '🇸🇰' },
  { code: 'SI', label: 'Slovenia', phoneCode: '+386', flag: '🇸🇮' },
  { code: 'SB', label: 'Solomon Islands', phoneCode: '+677', flag: '🇸🇧' },
  { code: 'SO', label: 'Somalia', phoneCode: '+252', flag: '🇸🇴' },
  { code: 'ZA', label: 'South Africa', phoneCode: '+27', flag: '🇿🇦' },
  { code: 'SS', label: 'South Sudan', phoneCode: '+211', flag: '🇸🇸' },
  { code: 'ES', label: 'Spain', phoneCode: '+34', flag: '🇪🇸' },
  { code: 'LK', label: 'Sri Lanka', phoneCode: '+94', flag: '🇱🇰' },
  { code: 'SD', label: 'Sudan', phoneCode: '+249', flag: '🇸🇩' },
  { code: 'SR', label: 'Suriname', phoneCode: '+597', flag: '🇸🇷' },
  { code: 'SJ', label: 'Svalbard and Jan Mayen', phoneCode: '+47', flag: '🇸🇯' },
  { code: 'SE', label: 'Sweden', phoneCode: '+46', flag: '🇸🇪' },
  { code: 'CH', label: 'Switzerland', phoneCode: '+41', flag: '🇨🇭' },
  { code: 'SY', label: 'Syria', phoneCode: '+963', flag: '🇸🇾' },
  { code: 'TW', label: 'Taiwan', phoneCode: '+886', flag: '🇹🇼' },
  { code: 'TJ', label: 'Tajikistan', phoneCode: '+992', flag: '🇹🇯' },
  { code: 'TZ', label: 'Tanzania', phoneCode: '+255', flag: '🇹🇿' },
  { code: 'TH', label: 'Thailand', phoneCode: '+66', flag: '🇹🇭' },
  { code: 'TL', label: 'Timor-Leste', phoneCode: '+670', flag: '🇹🇱' },
  { code: 'TG', label: 'Togo', phoneCode: '+228', flag: '🇹🇬' },
  { code: 'TK', label: 'Tokelau', phoneCode: '+690', flag: '🇹🇰' },
  { code: 'TO', label: 'Tonga', phoneCode: '+676', flag: '🇹🇴' },
  { code: 'TT', label: 'Trinidad and Tobago', phoneCode: '+1-868', flag: '🇹🇹' },
  { code: 'TN', label: 'Tunisia', phoneCode: '+216', flag: '🇹🇳' },
  { code: 'TR', label: 'Turkey', phoneCode: '+90', flag: '🇹🇷' },
  { code: 'TM', label: 'Turkmenistan', phoneCode: '+993', flag: '🇹🇲' },
  { code: 'TC', label: 'Turks and Caicos Islands', phoneCode: '+1-649', flag: '🇹🇨' },
  { code: 'TV', label: 'Tuvalu', phoneCode: '+688', flag: '🇹🇻' },
  { code: 'UG', label: 'Uganda', phoneCode: '+256', flag: '🇺🇬' },
  { code: 'UA', label: 'Ukraine', phoneCode: '+380', flag: '🇺🇦' },
  { code: 'AE', label: 'United Arab Emirates', phoneCode: '+971', flag: '🇦🇪' },
  { code: 'GB', label: 'United Kingdom', phoneCode: '+44', flag: '🇬🇧' },
  { code: 'US', label: 'United States', phoneCode: '+1', flag: '🇺🇸' },
  { code: 'UY', label: 'Uruguay', phoneCode: '+598', flag: '🇺🇾' },
  { code: 'UZ', label: 'Uzbekistan', phoneCode: '+998', flag: '🇺🇿' },
  { code: 'VU', label: 'Vanuatu', phoneCode: '+678', flag: '🇻🇺' },
  { code: 'VE', label: 'Venezuela', phoneCode: '+58', flag: '🇻🇪' },
  { code: 'VN', label: 'Vietnam', phoneCode: '+84', flag: '🇻🇳' },
  { code: 'WF', label: 'Wallis and Futuna', phoneCode: '+681', flag: '🇼🇫' },
  { code: 'YE', label: 'Yemen', phoneCode: '+967', flag: '🇾🇪' },
  { code: 'ZM', label: 'Zambia', phoneCode: '+260', flag: '🇿🇲' },
  { code: 'ZW', label: 'Zimbabwe', phoneCode: '+263', flag: '🇿🇼' }
]

export const allowedCountries = [
  { code: 'KZ', label: 'Kazakhstan', phoneCode: '+7', flag: '🇰🇿' },
  { code: 'RU', label: 'Russia', phoneCode: '+7', flag: '🇷🇺' },
  { code: 'CZ', label: 'Czech Republic', phoneCode: '+420', flag: '🇨🇿' }
]
